# Generated by Django 5.2.12 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_administrador",
            field=models.BooleanField(
                default=False, verbose_name="Administrador do Sistema"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_navegador",
            field=models.BooleanField(default=False, verbose_name="Navegador"),
        ),
    ]
